name: C/C++ CI Linux (gcc)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_gcc:
    runs-on: ubuntu-latest
    steps:
    - name: Get clang cache name
      id: date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash
    - name: Cache tools
      id: tools
      uses: actions/cache@v2
      with:
        path: ${{runner.workspace}}/tools/local
        key: ${{runner.os}}-phantomos-tools-gcc-${{steps.date.outputs.date}}
        restore-keys: ${{runner.os}}-phantomos-tools-
    - name: Add tools dir to path
      run: echo "${{runner.workspace}}/tools/local/bin" > $GITHUB_PATH
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true
    - name: x86_64-pc-phantom-kernel-gcc Build
      uses: LightningCreations/action-cmake-build@v1.2
      with:
        # C Compiler for toolchain
        cc: x86_64-pc-phantom-kernel-gcc # optional
        parallel: 8
        build-dir: ${{runner.workspace}}/build-gcc 
        configure-options: -DPHANTOMOS_USE_LINKER=gold


      

