name: C/C++ CI Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_clang:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true 
    - name: Clang Build
      uses: LightningCreations/action-cmake-build@v1.2
      with:
        # C Compiler for toolchain
        cc: clang # optional
        # C++ Compiler for toolchain
        cxx: clang++ # optional
        parallel: 8
        build-dir: ${{runner.workspace}}/build-clang 

