name: C/C++ CI Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_clang:
    runs-on: ubuntu-latest
    steps:
    - name: Install Build Dependencies
      run: |
         sudo apt install ninja-build
    - name: Cache tools
      id: tools
      uses: actions/cache@v2
      with:
        path: ${{runner.workspace}}/tools/local
        restore-keys: ${{runner.os}}-phantomos-tools-
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true
    - name: Clang Build
      uses: LightningCreations/action-cmake-build@v1.2
      with:
        # C Compiler for toolchain
        cc: ${{runner.workspace}}/tools/local/bin/clang # optional
        parallel: 8
        build-dir: ${{runner.workspace}}/build
        configure-options: -DPHANTOMOS_USE_LINKER=gold -GNinja -DCMAKE_C_FLAGS="-v"
        
        

