name: C/C++ CI OSX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true 
    - name: Clang Build
      uses:LightningCreations/action-cmake-build@v1.2
      with:
        # C Compiler for toolchain
        cc: clang # optional
        # C++ Compiler for toolchain
        cxx: clang++ # optional
        parallel: 8
        build-dir: ${{runner.workspace}}/build-clang 
